@startuml

class User {
  - id: int
  - name: string
  - email: string
  - passwordHash: string
  - createdAt: datetime
  + getName(): string
}

class UserManager{
  + register(name, email, password): User
  + login(email, password): User
  + logout(): void
  - checkValidation(name, email, password): array
}

class SearchManager{
  + searchThreadTitle(keyword): Thread[]
  + searchThreadUser(userName): Thread[]
}

abstract class Post {
  - id: int
  - content: string
  - userId: int
  - createdAt: datetime
  + getId(): int
  + getContent(): string
  + getUserId(): int
  + getCreatedAt(): string
  + update(title, content): void
  + delete(user): void
  + addReaction(user, reaction): void
}

class Thread {
  - title: string
  - userName: string
  - responseCount: int
  + create(userId, title, content): Thread
  + getTitle(): string
  + getAuthorName(): string
  + getResponseCount(): int
  + validate(title, content): array
  + getAllWithResponseCount(limit = 50, offset = 0): array
  + findById(id): ?self
}

class Response {
  - userName: string
  + create(userId, threadId ,content): Response
  + getUserName(): string
  + validateResponse(content): array
  + getByThreadId(threadId, limit = 500): array
}

class Admin {
  + updateUser(user): void
  + deleteUser(userId): void
  + updatePost(post, content): void
  + deletePost(post): void
}

class Reaction {
  - id: int
  - type: string
  - user: User
  - post: Post
  - createdAt: datetime
  + Reaction(user, post, type): Reaction
}

User ..> Post : 作成
Post --> Reaction : リアクション
Thread --|> Post
Response --|> Post
Admin --|> User
UserManager ..> User : 作成
@enduml